### ISSUE TITLE
question about reported result on NQ dataset

### ISSUE THREAD

**Issue by Rosarubu** [facebookresearch/FiD#3]
Hi there,

I notice that the reported value of NQ test on paper is 48.2(base) and 51.4(large), while in your repo, the result is 50.1(base) and 54.4(large).  What's the difference between them?

Also, when I run the `test_reader.py` to reproduce the result on test set, using DPR's retriever result (file from: retriever_results.nq.single.test.json) and nq_reader_base checkpoint downloaded through `get-model.sh`,  the EM I've got is 45.82, worse than 48.2 or 50.1. I check the passage id retrieved in DPR's result and the idx you provided, it seems not quit the same. Could you tell me how you retrieve the passages?  

Thanks a lot

**Comment by gizacard** [comment]
Hi, 

The released models have not been trained with DPR passages, they have been trained using the method developed in https://arxiv.org/abs/2012.04584 (with a modification in the architecture: instead of considering the cls token representation, representations of a sentence are averaged). If you train the reader with DPR passages you should obtain the results reported in "Leveraging Passage Retrieval with Generative Models".

**Comment by Xnhyacinth** [comment]
> Hi,
> 
> The released models have not been trained with DPR passages, they were trained using the method developed in https://arxiv.org/abs/2012.04584 (with a modification in the architecture: instead of considering the cls token representation, representations of a sentence are averaged). If you train the reader with DPR passages you should obtain the results reported in "Leveraging Passage Retrieval with Generative Models".

when I run the `test_reader.py` to reproduce the result on TQA test set, using data processed in `preprocess.py` and tqa_reader_base checkpoint downloaded through `get-model.sh`, the EM I got is 68.01, also worse than 77.1 in paper 'Leveraging Passage Retrieval with Generative Models'. So how can I reproduce the results in TQA? 
Thanks!
